[build-system]
requires = [
  "setuptools>=61",
  "wheel",
]
build-backend = "setuptools.build_meta:__legacy__"

[project]
name='scorep-jupyter'
version='0.0.1'
authors=[
  {name='Elias Werner',email='elias.werner@tu-dresden.de'},
]

dependencies = [
  "ipykernel",
  "jupyter-client",
  "astunparse",
  "scorep",
  "uuid",
  "dill"
]
