[build-system]
requires = [
  "setuptools>=61",
  "wheel",
]
build-backend = "setuptools.build_meta:__legacy__"

[project]
name='scorep-jupyter'
version='0.0.1'
authors=[
  {name='Elias Werner',email='elias.werner@tu-dresden.de'},
]
description='A'
license={ file="LICENSE" }
requires-python = ">=3.8"
classifiers=[
"Programming Language :: Python :: 3",
]

dependencies = [
  "ipykernel",
  "jupyter-client",
  "astunparse",
  "scorep==4.0.2",
  "uuid",
  "dill"
]
